import React, { useState } from 'react';
import { AlertTriangle, ShieldCheck } from 'lucide-react';

interface ResearchDisclaimerModalProps {
  isOpen: boolean;
  onAccept: () => void;
}

export const ResearchDisclaimerModal: React.FC<ResearchDisclaimerModalProps> = ({
  isOpen,
  onAccept
}) => {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const [acknowledged, setAcknowledged] = useState(false);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/75 backdrop-blur-xs">
      <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="bg-[#102E36] px-6 py-5 text-white flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-amber-500/20 border border-amber-400/40 flex items-center justify-center shrink-0">
            <AlertTriangle className="w-6 h-6 text-amber-400" />
          </div>
          <div>
            <h2 className="text-lg font-bold tracking-tight">Academic Research Disclaimer</h2>
            <p className="text-xs text-slate-300">Mandatory protocol acknowledgment before scan analysis</p>
          </div>
        </div>

        {/* Scrollable Content */}
        <div
          className="p-6 overflow-y-auto space-y-4 text-sm text-slate-700 leading-relaxed"
          onScroll={(e) => {
            const target = e.currentTarget;
            if (target.scrollHeight - target.scrollTop <= target.clientHeight + 40) {
              setHasScrolledToBottom(true);
            }
          }}
        >
          <div className="p-3.5 bg-amber-50 border border-amber-200 rounded-lg text-amber-900 text-xs font-medium">
            <strong>CRITICAL PROTOCOL NOTICE:</strong> LungNet is an experimental undergraduate research prototype. It is NOT a medical device, is NOT approved by the FDA or EMA, and must NEVER be used for clinical decision-making or diagnosis.
          </div>

          <h3 className="font-semibold text-slate-900 text-base">Key Academic & Clinical Constraints:</h3>
          <ul className="list-disc pl-5 space-y-2 text-xs text-slate-600">
            <li>
              <strong>Uncalibrated Relative Outputs:</strong> Model class scores (Benign, Malignant, Normal) represent mathematical softmax outputs from candidate convolutional features. They are <em>not calibrated cancer risks</em> or probability measures.
            </li>
            <li>
              <strong>Zero-Fabrication Policy:</strong> Real validated weights are currently pending patient-disjoint trial execution. In this environment, all inference results are generated in mock mode and visibly labeled with <span className="font-mono text-amber-800 font-semibold">[SYNTHETIC]</span>.
            </li>
            <li>
              <strong>Strict Patient-Disjoint Verification:</strong> Prior research notebooks exhibited data leakage from slice-level overlap. The LungNet system enforces strictly patient-partitioned manifests before any accuracy metric can be claimed.
            </li>
            <li>
              <strong>Required Human Expert Review:</strong> No classification result generated by this interface should ever be accepted without independent visual evaluation by a qualified medical professional.
            </li>
          </ul>

          <div className="pt-2">
            <label className="flex items-start gap-3 cursor-pointer p-3 rounded-lg border border-slate-200 bg-slate-50 hover:bg-slate-100 transition-colors">
              <input
                type="checkbox"
                checked={acknowledged}
                onChange={(e) => setAcknowledged(e.target.checked)}
                className="mt-0.5 w-4 h-4 rounded border-slate-300 text-[#126B67] focus:ring-[#126B67]"
              />
              <span className="text-xs font-medium text-slate-800">
                I understand that this interface is strictly for research demonstration, all scores without loaded weights are synthetic, and no output constitutes medical advice or calibrated diagnostic prediction.
              </span>
            </label>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
          <span className="text-xs text-slate-500 font-mono">
            {acknowledged ? "Terms accepted" : "Check authorization above to proceed"}
          </span>
          <button
            disabled={!acknowledged}
            onClick={onAccept}
            className="inline-flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-white bg-[#126B67] rounded-lg hover:bg-[#0D524F] disabled:opacity-40 disabled:cursor-not-allowed transition-all shadow-sm focus:ring-2 focus:ring-[#126B67] focus:ring-offset-1"
          >
            <ShieldCheck className="w-4 h-4" />
            <span>Acknowledge & Proceed</span>
          </button>
        </div>
      </div>
    </div>
  );
};
